version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - flask-shared:/data
    networks:
      - redis-network
  flask:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - flask-shared:/data
    environment:
      - FLASK_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - redis-network

volumes:
  flask-shared:

networks:
  redis-network:
    driver: bridge